// <auto-generated />
using System;
using DainnProductEAVManagement.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DainnProductEAVManagement.Migrations
{
    [DbContext(typeof(ProductCatalogDbContext))]
    [Migration("20251223081336_UpdatePrimaryKeysToGuid")]
    partial class UpdatePrimaryKeysToGuid
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DainnProductEAVManagement.Entities.AttributeGroup", b =>
                {
                    b.Property<Guid>("AttributeGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_group_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AttributeGroupName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("attribute_group_name");

                    b.Property<Guid>("AttributeSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_set_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("AttributeGroupId");

                    b.HasIndex("AttributeSetId");

                    b.ToTable("EavAttributeGroup", (string)null);

                    b.HasData(
                        new
                        {
                            AttributeGroupId = new Guid("22222222-2222-2222-2222-222222222222"),
                            AttributeGroupName = "General",
                            AttributeSetId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SortOrder = 1
                        },
                        new
                        {
                            AttributeGroupId = new Guid("33333333-3333-3333-3333-333333333333"),
                            AttributeGroupName = "Prices",
                            AttributeSetId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SortOrder = 2
                        },
                        new
                        {
                            AttributeGroupId = new Guid("44444444-4444-4444-4444-444444444444"),
                            AttributeGroupName = "Images",
                            AttributeSetId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SortOrder = 3
                        },
                        new
                        {
                            AttributeGroupId = new Guid("55555555-5555-5555-5555-555555555555"),
                            AttributeGroupName = "Meta Information",
                            AttributeSetId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SortOrder = 4
                        },
                        new
                        {
                            AttributeGroupId = new Guid("66666666-6666-6666-6666-666666666666"),
                            AttributeGroupName = "Content",
                            AttributeSetId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("DainnProductEAVManagement.Entities.AttributeSet", b =>
                {
                    b.Property<Guid>("AttributeSetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_set_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AttributeSetName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("attribute_set_name");

                    b.Property<int>("EntityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4)
                        .HasColumnName("entity_type_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("AttributeSetId");

                    b.ToTable("EavAttributeSet", (string)null);

                    b.HasData(
                        new
                        {
                            AttributeSetId = new Guid("11111111-1111-1111-1111-111111111111"),
                            AttributeSetName = "Default",
                            EntityTypeId = 4,
                            SortOrder = 1
                        });
                });

            modelBuilder.Entity("DainnProductEAVManagement.Entities.CategoryEntity", b =>
                {
                    b.Property<Guid>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("meta_description");

                    b.Property<string>("MetaKeywords")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("meta_keywords");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("meta_title");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("path");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UrlKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("url_key");

                    b.HasKey("EntityId");

                    b.HasIndex("ParentId");

                    b.ToTable("CategoryEntity", (string)null);
                });

            modelBuilder.Entity("DainnProductEAVManagement.Entities.EavAttribute", b =>
                {
                    b.Property<Guid>("AttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AttributeCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("attribute_code");

                    b.Property<Guid?>("AttributeGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_group_id");

                    b.Property<string>("BackendType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("backend_type");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("default_value");

                    b.Property<int>("EntityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4)
                        .HasColumnName("entity_type_id");

                    b.Property<string>("FrontendInput")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("frontend_input");

                    b.Property<string>("FrontendLabel")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("frontend_label");

                    b.Property<bool>("IsComparable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_comparable");

                    b.Property<bool>("IsFilterable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_filterable");

                    b.Property<bool>("IsHtmlAllowedOnFront")
                        .HasColumnType("boolean")
                        .HasColumnName("is_html_allowed_on_front");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<bool>("IsSearchable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_searchable");

                    b.Property<bool>("IsUnique")
                        .HasColumnType("boolean")
                        .HasColumnName("is_unique");

                    b.Property<bool>("IsUsedForPromoRules")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used_for_promo_rules");

                    b.Property<bool>("IsVisibleOnFront")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible_on_front");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note");

                    b.Property<int?>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("AttributeId");

                    b.HasIndex("AttributeGroupId");

                    b.HasIndex("EntityTypeId", "AttributeCode")
                        .IsUnique();

                    b.ToTable("EavAttribute", (string)null);

                    b.HasData(
                        new
                        {
                            AttributeId = new Guid("10000000-0000-0000-0000-000000000001"),
                            AttributeCode = "name",
                            AttributeGroupId = new Guid("22222222-2222-2222-2222-222222222222"),
                            BackendType = "varchar",
                            EntityTypeId = 4,
                            FrontendInput = "text",
                            FrontendLabel = "Product Name",
                            IsComparable = false,
                            IsFilterable = false,
                            IsHtmlAllowedOnFront = false,
                            IsRequired = true,
                            IsSearchable = true,
                            IsUnique = false,
                            IsUsedForPromoRules = false,
                            IsVisibleOnFront = true
                        },
                        new
                        {
                            AttributeId = new Guid("10000000-0000-0000-0000-000000000002"),
                            AttributeCode = "description",
                            AttributeGroupId = new Guid("66666666-6666-6666-6666-666666666666"),
                            BackendType = "text",
                            EntityTypeId = 4,
                            FrontendInput = "textarea",
                            FrontendLabel = "Description",
                            IsComparable = false,
                            IsFilterable = false,
                            IsHtmlAllowedOnFront = true,
                            IsRequired = false,
                            IsSearchable = true,
                            IsUnique = false,
                            IsUsedForPromoRules = false,
                            IsVisibleOnFront = true
                        },
                        new
                        {
                            AttributeId = new Guid("10000000-0000-0000-0000-000000000003"),
                            AttributeCode = "short_description",
                            AttributeGroupId = new Guid("66666666-6666-6666-6666-666666666666"),
                            BackendType = "text",
                            EntityTypeId = 4,
                            FrontendInput = "textarea",
                            FrontendLabel = "Short Description",
                            IsComparable = false,
                            IsFilterable = false,
                            IsHtmlAllowedOnFront = true,
                            IsRequired = false,
                            IsSearchable = true,
                            IsUnique = false,
                            IsUsedForPromoRules = false,
                            IsVisibleOnFront = true
                        },
                        new
                        {
                            AttributeId = new Guid("10000000-0000-0000-0000-000000000004"),
                            AttributeCode = "price",
                            AttributeGroupId = new Guid("33333333-3333-3333-3333-333333333333"),
                            BackendType = "decimal",
                            EntityTypeId = 4,
                            FrontendInput = "price",
                            FrontendLabel = "Price",
                            IsComparable = true,
                            IsFilterable = true,
                            IsHtmlAllowedOnFront = false,
                            IsRequired = true,
                            IsSearchable = true,
                            IsUnique = false,
                            IsUsedForPromoRules = false,
                            IsVisibleOnFront = true
                        },
                        new
                        {
                            AttributeId = new Guid("10000000-0000-0000-0000-000000000005"),
                            AttributeCode = "special_price",
                            AttributeGroupId = new Guid("33333333-3333-3333-3333-333333333333"),
                            BackendType = "decimal",
                            EntityTypeId = 4,
                            FrontendInput = "price",
                            FrontendLabel = "Special Price",
                            IsComparable = false,
                            IsFilterable = true,
                            IsHtmlAllowedOnFront = false,
                            IsRequired = false,
                            IsSearchable = false,
                            IsUnique = false,
                            IsUsedForPromoRules = false,
                            IsVisibleOnFront = true
                        },
                        new
                        {
                            AttributeId = new Guid("10000000-0000-0000-0000-000000000006"),
                            AttributeCode = "status",
                            AttributeGroupId = new Guid("22222222-2222-2222-2222-222222222222"),
                            BackendType = "int",
                            DefaultValue = "1",
                            EntityTypeId = 4,
                            FrontendInput = "select",
                            FrontendLabel = "Status",
                            IsComparable = false,
                            IsFilterable = false,
                            IsHtmlAllowedOnFront = false,
                            IsRequired = true,
                            IsSearchable = false,
                            IsUnique = false,
                            IsUsedForPromoRules = false,
                            IsVisibleOnFront = true
                        },
                        new
                        {
                            AttributeId = new Guid("10000000-0000-0000-0000-000000000007"),
                            AttributeCode = "visibility",
                            AttributeGroupId = new Guid("22222222-2222-2222-2222-222222222222"),
                            BackendType = "int",
                            DefaultValue = "4",
                            EntityTypeId = 4,
                            FrontendInput = "select",
                            FrontendLabel = "Visibility",
                            IsComparable = false,
                            IsFilterable = false,
                            IsHtmlAllowedOnFront = false,
                            IsRequired = true,
                            IsSearchable = false,
                            IsUnique = false,
                            IsUsedForPromoRules = false,
                            IsVisibleOnFront = true
                        },
                        new
                        {
                            AttributeId = new Guid("10000000-0000-0000-0000-000000000008"),
                            AttributeCode = "weight",
                            AttributeGroupId = new Guid("22222222-2222-2222-2222-222222222222"),
                            BackendType = "decimal",
                            EntityTypeId = 4,
                            FrontendInput = "text",
                            FrontendLabel = "Weight",
                            IsComparable = false,
                            IsFilterable = false,
                            IsHtmlAllowedOnFront = false,
                            IsRequired = false,
                            IsSearchable = false,
                            IsUnique = false,
                            IsUsedForPromoRules = false,
                            IsVisibleOnFront = true
                        },
                        new
                        {
                            AttributeId = new Guid("10000000-0000-0000-0000-000000000009"),
                            AttributeCode = "url_key",
                            AttributeGroupId = new Guid("55555555-5555-5555-5555-555555555555"),
                            BackendType = "varchar",
                            EntityTypeId = 4,
                            FrontendInput = "text",
                            FrontendLabel = "URL Key",
                            IsComparable = false,
                            IsFilterable = false,
                            IsHtmlAllowedOnFront = false,
                            IsRequired = false,
                            IsSearchable = false,
                            IsUnique = true,
                            IsUsedForPromoRules = false,
                            IsVisibleOnFront = true
                        },
                        new
                        {
                            AttributeId = new Guid("10000000-0000-0000-0000-00000000000a"),
                            AttributeCode = "meta_title",
                            AttributeGroupId = new Guid("55555555-5555-5555-5555-555555555555"),
                            BackendType = "varchar",
                            EntityTypeId = 4,
                            FrontendInput = "text",
                            FrontendLabel = "Meta Title",
                            IsComparable = false,
                            IsFilterable = false,
                            IsHtmlAllowedOnFront = false,
                            IsRequired = false,
                            IsSearchable = false,
                            IsUnique = false,
                            IsUsedForPromoRules = false,
                            IsVisibleOnFront = true
                        },
                        new
                        {
                            AttributeId = new Guid("10000000-0000-0000-0000-00000000000b"),
                            AttributeCode = "meta_description",
                            AttributeGroupId = new Guid("55555555-5555-5555-5555-555555555555"),
                            BackendType = "text",
                            EntityTypeId = 4,
                            FrontendInput = "textarea",
                            FrontendLabel = "Meta Description",
                            IsComparable = false,
                            IsFilterable = false,
                            IsHtmlAllowedOnFront = false,
                            IsRequired = false,
                            IsSearchable = false,
                            IsUnique = false,
                            IsUsedForPromoRules = false,
                            IsVisibleOnFront = true
                        },
                        new
                        {
                            AttributeId = new Guid("10000000-0000-0000-0000-00000000000c"),
                            AttributeCode = "meta_keywords",
                            AttributeGroupId = new Guid("55555555-5555-5555-5555-555555555555"),
                            BackendType = "text",
                            EntityTypeId = 4,
                            FrontendInput = "textarea",
                            FrontendLabel = "Meta Keywords",
                            IsComparable = false,
                            IsFilterable = false,
                            IsHtmlAllowedOnFront = false,
                            IsRequired = false,
                            IsSearchable = false,
                            IsUnique = false,
                            IsUsedForPromoRules = false,
                            IsVisibleOnFront = true
                        },
                        new
                        {
                            AttributeId = new Guid("10000000-0000-0000-0000-00000000000d"),
                            AttributeCode = "image",
                            AttributeGroupId = new Guid("44444444-4444-4444-4444-444444444444"),
                            BackendType = "varchar",
                            EntityTypeId = 4,
                            FrontendInput = "media_image",
                            FrontendLabel = "Base Image",
                            IsComparable = false,
                            IsFilterable = false,
                            IsHtmlAllowedOnFront = false,
                            IsRequired = false,
                            IsSearchable = false,
                            IsUnique = false,
                            IsUsedForPromoRules = false,
                            IsVisibleOnFront = true
                        },
                        new
                        {
                            AttributeId = new Guid("10000000-0000-0000-0000-00000000000e"),
                            AttributeCode = "small_image",
                            AttributeGroupId = new Guid("44444444-4444-4444-4444-444444444444"),
                            BackendType = "varchar",
                            EntityTypeId = 4,
                            FrontendInput = "media_image",
                            FrontendLabel = "Small Image",
                            IsComparable = false,
                            IsFilterable = false,
                            IsHtmlAllowedOnFront = false,
                            IsRequired = false,
                            IsSearchable = false,
                            IsUnique = false,
                            IsUsedForPromoRules = false,
                            IsVisibleOnFront = true
                        },
                        new
                        {
                            AttributeId = new Guid("10000000-0000-0000-0000-00000000000f"),
                            AttributeCode = "thumbnail",
                            AttributeGroupId = new Guid("44444444-4444-4444-4444-444444444444"),
                            BackendType = "varchar",
                            EntityTypeId = 4,
                            FrontendInput = "media_image",
                            FrontendLabel = "Thumbnail",
                            IsComparable = false,
                            IsFilterable = false,
                            IsHtmlAllowedOnFront = false,
                            IsRequired = false,
                            IsSearchable = false,
                            IsUnique = false,
                            IsUsedForPromoRules = false,
                            IsVisibleOnFront = true
                        },
                        new
                        {
                            AttributeId = new Guid("10000000-0000-0000-0000-000000000010"),
                            AttributeCode = "color",
                            AttributeGroupId = new Guid("22222222-2222-2222-2222-222222222222"),
                            BackendType = "int",
                            EntityTypeId = 4,
                            FrontendInput = "select",
                            FrontendLabel = "Color",
                            IsComparable = true,
                            IsFilterable = true,
                            IsHtmlAllowedOnFront = false,
                            IsRequired = false,
                            IsSearchable = false,
                            IsUnique = false,
                            IsUsedForPromoRules = false,
                            IsVisibleOnFront = true
                        },
                        new
                        {
                            AttributeId = new Guid("10000000-0000-0000-0000-000000000011"),
                            AttributeCode = "size",
                            AttributeGroupId = new Guid("22222222-2222-2222-2222-222222222222"),
                            BackendType = "int",
                            EntityTypeId = 4,
                            FrontendInput = "select",
                            FrontendLabel = "Size",
                            IsComparable = true,
                            IsFilterable = true,
                            IsHtmlAllowedOnFront = false,
                            IsRequired = false,
                            IsSearchable = false,
                            IsUnique = false,
                            IsUsedForPromoRules = false,
                            IsVisibleOnFront = true
                        },
                        new
                        {
                            AttributeId = new Guid("10000000-0000-0000-0000-000000000012"),
                            AttributeCode = "manufacturer",
                            AttributeGroupId = new Guid("22222222-2222-2222-2222-222222222222"),
                            BackendType = "varchar",
                            EntityTypeId = 4,
                            FrontendInput = "select",
                            FrontendLabel = "Manufacturer",
                            IsComparable = false,
                            IsFilterable = true,
                            IsHtmlAllowedOnFront = false,
                            IsRequired = false,
                            IsSearchable = false,
                            IsUnique = false,
                            IsUsedForPromoRules = false,
                            IsVisibleOnFront = true
                        },
                        new
                        {
                            AttributeId = new Guid("10000000-0000-0000-0000-000000000013"),
                            AttributeCode = "special_from_date",
                            AttributeGroupId = new Guid("33333333-3333-3333-3333-333333333333"),
                            BackendType = "datetime",
                            EntityTypeId = 4,
                            FrontendInput = "date",
                            FrontendLabel = "Special Price From Date",
                            IsComparable = false,
                            IsFilterable = false,
                            IsHtmlAllowedOnFront = false,
                            IsRequired = false,
                            IsSearchable = false,
                            IsUnique = false,
                            IsUsedForPromoRules = false,
                            IsVisibleOnFront = true
                        },
                        new
                        {
                            AttributeId = new Guid("10000000-0000-0000-0000-000000000014"),
                            AttributeCode = "special_to_date",
                            AttributeGroupId = new Guid("33333333-3333-3333-3333-333333333333"),
                            BackendType = "datetime",
                            EntityTypeId = 4,
                            FrontendInput = "date",
                            FrontendLabel = "Special Price To Date",
                            IsComparable = false,
                            IsFilterable = false,
                            IsHtmlAllowedOnFront = false,
                            IsRequired = false,
                            IsSearchable = false,
                            IsUnique = false,
                            IsUsedForPromoRules = false,
                            IsVisibleOnFront = true
                        });
                });

            modelBuilder.Entity("DainnProductEAVManagement.Entities.ProductCategoryRelation", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategory", (string)null);
                });

            modelBuilder.Entity("DainnProductEAVManagement.Entities.ProductEntity", b =>
                {
                    b.Property<Guid>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AttributeSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_set_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("simple")
                        .HasColumnName("type_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("EntityId");

                    b.HasIndex("AttributeSetId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("ProductEntity", (string)null);
                });

            modelBuilder.Entity("DainnProductEAVManagement.Entities.ProductInventory", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<bool>("BackOrders")
                        .HasColumnType("boolean")
                        .HasColumnName("backorders");

                    b.Property<bool>("IsInStock")
                        .HasColumnType("boolean")
                        .HasColumnName("is_in_stock");

                    b.Property<bool>("ManageStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("manage_stock");

                    b.Property<int>("MaxSaleQty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10000)
                        .HasColumnName("max_sale_qty");

                    b.Property<int>("MinQty")
                        .HasColumnType("integer")
                        .HasColumnName("min_qty");

                    b.Property<int>("MinSaleQty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("min_sale_qty");

                    b.Property<int?>("NotifyStockQty")
                        .HasColumnType("integer")
                        .HasColumnName("notify_stock_qty");

                    b.Property<int>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.Property<decimal?>("QtyIncrement")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("qty_increments");

                    b.HasKey("ProductId");

                    b.ToTable("ProductInventory", (string)null);
                });

            modelBuilder.Entity("DainnProductEAVManagement.Entities.ProductMediaGallery", b =>
                {
                    b.Property<Guid>("ValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("value_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AltText")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("alt_text");

                    b.Property<Guid>("AttributeId")
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_id");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("disabled");

                    b.Property<bool>("IsBaseImage")
                        .HasColumnType("boolean")
                        .HasColumnName("is_base_image");

                    b.Property<bool>("IsSmallImage")
                        .HasColumnType("boolean")
                        .HasColumnName("is_small_image");

                    b.Property<bool>("IsSwatchImage")
                        .HasColumnType("boolean")
                        .HasColumnName("is_swatch_image");

                    b.Property<bool>("IsThumbnail")
                        .HasColumnType("boolean")
                        .HasColumnName("is_thumbnail");

                    b.Property<string>("Label")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("label");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("image")
                        .HasColumnName("media_type");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("store_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("value");

                    b.HasKey("ValueId");

                    b.HasIndex("AttributeId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductMediaGallery", (string)null);
                });

            modelBuilder.Entity("DainnProductEAVManagement.Entities.ProductPrice", b =>
                {
                    b.Property<Guid>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("price_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("CustomerGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("customer_group_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(20, 6)
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("price");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Qty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("qty");

                    b.Property<DateTime?>("SpecialFromDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("special_from_date");

                    b.Property<decimal?>("SpecialPrice")
                        .HasPrecision(20, 6)
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("special_price");

                    b.Property<DateTime?>("SpecialToDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("special_to_date");

                    b.Property<int>("WebsiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("website_id");

                    b.HasKey("PriceId");

                    b.HasIndex("ProductId", "CustomerGroupId", "WebsiteId", "Qty")
                        .IsUnique();

                    b.ToTable("ProductPrice", (string)null);
                });

            modelBuilder.Entity("DainnProductEAVManagement.Entities.ProductRelation", b =>
                {
                    b.Property<Guid>("RelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("relation_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("super")
                        .HasColumnName("relation_type");

                    b.HasKey("RelationId");

                    b.HasIndex("ChildId");

                    b.HasIndex("ParentId", "ChildId", "RelationType")
                        .IsUnique();

                    b.ToTable("ProductRelation", (string)null);
                });

            modelBuilder.Entity("DainnProductEAVManagement.Entities.ProductWebsite", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("WebsiteId")
                        .HasColumnType("integer")
                        .HasColumnName("website_id");

                    b.HasKey("ProductId", "WebsiteId");

                    b.ToTable("ProductWebsite", (string)null);
                });

            modelBuilder.Entity("DainnProductEAVManagement.ValueEntities.ProductDatetimeValue", b =>
                {
                    b.Property<Guid>("ValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("value_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AttributeId")
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_id");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("store_id");

                    b.Property<DateTime?>("Value")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("value");

                    b.HasKey("ValueId");

                    b.HasIndex("AttributeId");

                    b.HasIndex("EntityId", "AttributeId", "StoreId")
                        .IsUnique();

                    b.ToTable("ProductEntityDatetime", (string)null);
                });

            modelBuilder.Entity("DainnProductEAVManagement.ValueEntities.ProductDecimalValue", b =>
                {
                    b.Property<Guid>("ValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("value_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AttributeId")
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_id");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("store_id");

                    b.Property<decimal?>("Value")
                        .HasPrecision(20, 6)
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("value");

                    b.HasKey("ValueId");

                    b.HasIndex("AttributeId");

                    b.HasIndex("EntityId", "AttributeId", "StoreId")
                        .IsUnique();

                    b.ToTable("ProductEntityDecimal", (string)null);
                });

            modelBuilder.Entity("DainnProductEAVManagement.ValueEntities.ProductIntValue", b =>
                {
                    b.Property<Guid>("ValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("value_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AttributeId")
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_id");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("store_id");

                    b.Property<int?>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("ValueId");

                    b.HasIndex("AttributeId");

                    b.HasIndex("EntityId", "AttributeId", "StoreId")
                        .IsUnique();

                    b.ToTable("ProductEntityInt", (string)null);
                });

            modelBuilder.Entity("DainnProductEAVManagement.ValueEntities.ProductTextValue", b =>
                {
                    b.Property<Guid>("ValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("value_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AttributeId")
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_id");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("store_id");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("ValueId");

                    b.HasIndex("AttributeId");

                    b.HasIndex("EntityId", "AttributeId", "StoreId")
                        .IsUnique();

                    b.ToTable("ProductEntityText", (string)null);
                });

            modelBuilder.Entity("DainnProductEAVManagement.ValueEntities.ProductVarcharValue", b =>
                {
                    b.Property<Guid>("ValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("value_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AttributeId")
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_id");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("store_id");

                    b.Property<string>("Value")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("value");

                    b.HasKey("ValueId");

                    b.HasIndex("AttributeId");

                    b.HasIndex("EntityId", "AttributeId", "StoreId")
                        .IsUnique();

                    b.ToTable("ProductEntityVarchar", (string)null);
                });

            modelBuilder.Entity("DainnProductEAVManagement.Entities.AttributeGroup", b =>
                {
                    b.HasOne("DainnProductEAVManagement.Entities.AttributeSet", "AttributeSet")
                        .WithMany("Groups")
                        .HasForeignKey("AttributeSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeSet");
                });

            modelBuilder.Entity("DainnProductEAVManagement.Entities.CategoryEntity", b =>
                {
                    b.HasOne("DainnProductEAVManagement.Entities.CategoryEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DainnProductEAVManagement.Entities.EavAttribute", b =>
                {
                    b.HasOne("DainnProductEAVManagement.Entities.AttributeGroup", "Group")
                        .WithMany("Attributes")
                        .HasForeignKey("AttributeGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("DainnProductEAVManagement.Entities.ProductCategoryRelation", b =>
                {
                    b.HasOne("DainnProductEAVManagement.Entities.CategoryEntity", "Category")
                        .WithMany("ProductRelations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DainnProductEAVManagement.Entities.ProductEntity", "Product")
                        .WithMany("CategoryRelations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DainnProductEAVManagement.Entities.ProductEntity", b =>
                {
                    b.HasOne("DainnProductEAVManagement.Entities.AttributeSet", "AttributeSet")
                        .WithMany("Products")
                        .HasForeignKey("AttributeSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AttributeSet");
                });

            modelBuilder.Entity("DainnProductEAVManagement.Entities.ProductInventory", b =>
                {
                    b.HasOne("DainnProductEAVManagement.Entities.ProductEntity", "Product")
                        .WithOne("Inventory")
                        .HasForeignKey("DainnProductEAVManagement.Entities.ProductInventory", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DainnProductEAVManagement.Entities.ProductMediaGallery", b =>
                {
                    b.HasOne("DainnProductEAVManagement.Entities.EavAttribute", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DainnProductEAVManagement.Entities.ProductEntity", "Product")
                        .WithMany("MediaGallery")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DainnProductEAVManagement.Entities.ProductPrice", b =>
                {
                    b.HasOne("DainnProductEAVManagement.Entities.ProductEntity", "Product")
                        .WithMany("Prices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DainnProductEAVManagement.Entities.ProductRelation", b =>
                {
                    b.HasOne("DainnProductEAVManagement.Entities.ProductEntity", "Child")
                        .WithMany("ParentRelations")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DainnProductEAVManagement.Entities.ProductEntity", "Parent")
                        .WithMany("ChildRelations")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DainnProductEAVManagement.Entities.ProductWebsite", b =>
                {
                    b.HasOne("DainnProductEAVManagement.Entities.ProductEntity", "Product")
                        .WithMany("Websites")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DainnProductEAVManagement.ValueEntities.ProductDatetimeValue", b =>
                {
                    b.HasOne("DainnProductEAVManagement.Entities.EavAttribute", "Attribute")
                        .WithMany("DatetimeValues")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DainnProductEAVManagement.Entities.ProductEntity", "Product")
                        .WithMany("DatetimeValues")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DainnProductEAVManagement.ValueEntities.ProductDecimalValue", b =>
                {
                    b.HasOne("DainnProductEAVManagement.Entities.EavAttribute", "Attribute")
                        .WithMany("DecimalValues")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DainnProductEAVManagement.Entities.ProductEntity", "Product")
                        .WithMany("DecimalValues")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DainnProductEAVManagement.ValueEntities.ProductIntValue", b =>
                {
                    b.HasOne("DainnProductEAVManagement.Entities.EavAttribute", "Attribute")
                        .WithMany("IntValues")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DainnProductEAVManagement.Entities.ProductEntity", "Product")
                        .WithMany("IntValues")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DainnProductEAVManagement.ValueEntities.ProductTextValue", b =>
                {
                    b.HasOne("DainnProductEAVManagement.Entities.EavAttribute", "Attribute")
                        .WithMany("TextValues")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DainnProductEAVManagement.Entities.ProductEntity", "Product")
                        .WithMany("TextValues")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DainnProductEAVManagement.ValueEntities.ProductVarcharValue", b =>
                {
                    b.HasOne("DainnProductEAVManagement.Entities.EavAttribute", "Attribute")
                        .WithMany("VarcharValues")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DainnProductEAVManagement.Entities.ProductEntity", "Product")
                        .WithMany("VarcharValues")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DainnProductEAVManagement.Entities.AttributeGroup", b =>
                {
                    b.Navigation("Attributes");
                });

            modelBuilder.Entity("DainnProductEAVManagement.Entities.AttributeSet", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("DainnProductEAVManagement.Entities.CategoryEntity", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("ProductRelations");
                });

            modelBuilder.Entity("DainnProductEAVManagement.Entities.EavAttribute", b =>
                {
                    b.Navigation("DatetimeValues");

                    b.Navigation("DecimalValues");

                    b.Navigation("IntValues");

                    b.Navigation("TextValues");

                    b.Navigation("VarcharValues");
                });

            modelBuilder.Entity("DainnProductEAVManagement.Entities.ProductEntity", b =>
                {
                    b.Navigation("CategoryRelations");

                    b.Navigation("ChildRelations");

                    b.Navigation("DatetimeValues");

                    b.Navigation("DecimalValues");

                    b.Navigation("IntValues");

                    b.Navigation("Inventory");

                    b.Navigation("MediaGallery");

                    b.Navigation("ParentRelations");

                    b.Navigation("Prices");

                    b.Navigation("TextValues");

                    b.Navigation("VarcharValues");

                    b.Navigation("Websites");
                });
#pragma warning restore 612, 618
        }
    }
}
